import "./globals.css";

import { Inter as FontSans } from "next/font/google";
import Navbar from "../components/navbar";

import { cn } from "@app/client/lib/utils";
import { ThemeProvider } from "../components/ui/theme-provider";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen w-full xl:max-w-[1600px] flex  flex-col justif-center mx-auto  bg-backgrond font-sans antialiased",
          fontSans.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex justify-center flex-col items-center">
            {children}
          </div>
        </ThemeProvider>
        {/* <Navbar /> */}
      </body>
    </html>
  );
}
